# Use publikum/password user/password credentials
version: '3.1'

services:

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
