steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/mmmtrifork/trifork-chat-app', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/github.com/mmmtrifork/trifork-chat-app']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'trifork-chat-app', '--image', 'gcr.io/$PROJECT_ID/github.com/mmmtrifork/trifork-chat-app', '--region', 'us-central1', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/github.com/mmmtrifork/trifork-chat-app